# fly.toml app configuration file generated for athleis-sync on 2024-02-14T14:20:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'athleis-sync'
primary_region = 'cdg'

[build]
  image = 'electricsql/electric'

[env]
  AUTH_MODE = 'secure'
  ELECTRIC_WRITE_TO_PG_MODE = 'direct_writes'

[http_service]
  internal_port = 5133
  force_https = true

[[http_service.checks]]
    interval = '10s'
    timeout = '1s'
    grace_period = '20s'
    method = 'GET'
    path = '/api/status'

[[services]]
  protocol = 'tcp'
  internal_port = 65432

[[services.ports]]
    port = 65432
    handlers = ['pg_tls']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
