export enum TableName {
  PROFILES = "profiles",
  EXERCICES = "exercices",
  GROUPS = "groups",
  EXERCICES_GROUPS = "exercices_groups",
  EQUIPMENTS = "equipments",
  EXERCICES_EQUIPMENTS = "exercices_equipments",
  MEDIAS = "medias",
  EXERCICES_MEDIAS = "exercices_medias",
  TRAINING = "trainings",
  TRAINING_STEPS = "trainings_steps",
  TRAINING_SUPERSETS = "trainings_supersets",
  TRAINING_EXERCICES = "trainings_exercices",
  TRAINING_EXERCICE_SERIES = "trainings_exercices_series",
}
